# Generated by Django 3.2.4 on 2021-06-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0002_alter_tipodocumento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='estado',
            field=models.CharField(choices=[('1', 'ACTIVO'), ('2', 'INACTIVO')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
