# Generated by Django 3.2 on 2021-06-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0004_estadocivil'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='abreviado',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
