# Generated by Django 3.2.4 on 2021-06-17 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'ACTIVO'), ('2', 'VALIDADO EN AREA'), ('3', 'VALIDADO EN PERSONAL'), ('4', 'OBSERVADO EN PERSONAL'), ('5', 'ACEPTADO DIRECTOR'), ('6', 'OBSERVADO DIRECTOR')], max_length=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('abreviado', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('numero_documento', models.CharField(max_length=11)),
                ('estado', models.CharField(max_length=1)),
                ('sexo', models.CharField(choices=[('1', 'MASCULINO'), ('2', 'FEMENINO')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.cargo')),
                ('estadocivil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.estadocivil')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.tipodocumento')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('1', 'ACTIVO'), ('2', 'INACTIVO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSistemaPesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('abreviado', models.CharField(max_length=6)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RolPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.SmallIntegerField()),
                ('mes', models.CharField(choices=[('01', 'ENERO'), ('02', 'FEBRERO'), ('03', 'MARZO'), ('04', 'ABRIL'), ('05', 'MAYO'), ('06', 'JUNIO'), ('07', 'JULIO'), ('08', 'AGOSTO'), ('09', 'SEPTIEMBRE'), ('10', 'OCTUBRE'), ('11', 'NOVIEMBRE'), ('12', 'DICIEMBRE')], max_length=2)),
                ('estado', models.CharField(choices=[('1', 'ACTIVO'), ('2', 'ENVIADO'), ('3', 'APROBADO'), ('4', 'OBSERVADO')], max_length=1)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.areas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Remuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_bruto', models.DecimalField(decimal_places=3, max_digits=9)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'APERTURADO'), ('2', 'CERRADO')], max_length=1)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'ABIERTO'), ('2', 'CERRADO')], max_length=1)),
                ('mes', models.CharField(max_length=2)),
                ('anio', models.IntegerField()),
                ('total_descuento', models.DecimalField(decimal_places=2, default='0.00', max_digits=9)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.personal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRolPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateField()),
                ('hora_fin', models.DateField()),
                ('check', models.BooleanField(default=False)),
                ('detallerol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.detallerol')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.personal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.turno')),
            ],
        ),
        migrations.AddField(
            model_name='detallerol',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.personal'),
        ),
        migrations.AddField(
            model_name='detallerol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.rolpersonal'),
        ),
        migrations.CreateModel(
            name='DetalleRemuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sistema_pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tiposistemapesiones')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, default='0.00', max_digits=9)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_permiso', models.DateTimeField()),
                ('hora_salida', models.TimeField()),
                ('hora_entrada', models.TimeField()),
                ('fechahora_registro', models.DateTimeField(auto_now=True)),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tipopermiso')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoxPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estado', models.CharField(choices=[('1', 'ACTIVO'), ('2', 'INACTIVO')], max_length=1)),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tipopermiso')),
            ],
        ),
    ]
