# Generated by Django 3.2.4 on 2021-06-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0004_estadocivil'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='estadocivil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestro.estadocivil'),
        ),
        migrations.DeleteModel(
            name='EstadoCivil',
        ),
    ]
