# Generated by Django 3.2.4 on 2021-06-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0004_estadocivil'),
        ('rrhh', '0002_auto_20210617_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestro.areas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='estado',
            field=models.CharField(choices=[('1', 'ACTIVO'), ('2', 'INACTIVO')], max_length=1),
        ),
    ]
