# Generated by Django 3.2 on 2021-06-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_auto_20210617_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_rol', to='rrhh.rolpersonal'),
        ),
    ]
