# Generated by Django 3.2 on 2021-06-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_alter_detallerol_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerolpersonal',
            options={'verbose_name': 'Detalle Rol Personal', 'verbose_name_plural': 'Detalles Roles Personales'},
        ),
    ]
