# Generated by Django 3.2 on 2021-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_alter_detallerolpersonal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerolpersonal',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='detallerolpersonal',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
