# Generated by Django 3.2 on 2021-06-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_auto_20210621_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerol',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.personal'),
        ),
    ]
