# Generated by Django 3.2 on 2021-06-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_alter_detallerol_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.rolpersonal'),
        ),
    ]
