# Generated by Django 3.2 on 2021-06-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_alter_detallerol_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='total_permiso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
