# Generated by Django 3.2 on 2021-06-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_auto_20210626_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepermiso',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='detallepermiso',
            name='hora_salida',
        ),
    ]
