# Generated by Django 3.2 on 2021-06-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_auto_20210626_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='total_descuento',
        ),
        migrations.AddField(
            model_name='detallepermiso',
            name='permiso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rrhh.permiso'),
            preserve_default=False,
        ),
    ]
