# Generated by Django 3.2 on 2021-06-27 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestro', '0005_turno_abreviado'),
        ('rrhh', '0014_alter_detallepermiso_fecha_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField()),
                ('estado', models.CharField(choices=[('1', 'APERTURADO'), ('2', 'CERRADO')], max_length=1)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.personal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('tipo_marcacion', models.CharField(choices=[('1', 'INGRESO'), ('2', 'SALIDA')], max_length=1)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='photography_attached', verbose_name='imagen')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistencia')),
                ('detallerolpersonal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detallerolpersonal', to='rrhh.detallerolpersonal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.turno')),
            ],
        ),
    ]
